### ISSUE TITLE
Usage without .pinyarn.json

### ISSUE THREAD

**Issue by deini** [sysgears/pinyarn#2]
👋  What are your thoughts on having a flag to disable the `.pinyarn.json` generation? Assuming I'm aware of the limitations of using stable releases only.

**Comment by larixer** [comment]
@deini Fine by me, this is how I initially implemented it, without that json, its a bit of mixing of concerns though, keeping configuration separately looks more sane to me, but I'm fine with adding the flags for different modes of operation, this tool should be flexible

**Comment by larixer** [comment]
Hey @deini 
This is fixed now via: https://github.com/sysgears/pinyarn/commit/83cd2c2e420f2b1b03c687197788a92e1ebf90ac
