### ISSUE TITLE
updating yarn (publishing bug explanation?)

### ISSUE THREAD

**Issue by PAStheLoD** [sysgears/pinyarn#3]
Hello,

First of all thanks for this great utility package, works like a charm!

So, I'd like to understand if there are any obstacles to updating the pinned yarn version. In particular, looking at the commits there's a mention of some kind of publishing bug, but the commit messages (and the contents of the commits) don't give sufficient context and explanation (to me). Could you please help with this? Thanks again!

I'm mostly asking because [this bug](https://github.com/yarnpkg/berry/issues/3597) on Node 17 affects the pinned version.

**Comment by larixer** [comment]
The publishing bug referenced in commit was related to difficulties with publishing `pinyarn` itself with Yarn Modern, while it was still possible to publish it with `npm`. It is unrelated to `pinyarn` functionality at all.
