### ISSUE TITLE
GitHub tokens expired

### ISSUE THREAD

**Issue by smmr0** [sysgears/pinyarn#4]
When attempting to run, I get the following error:

```
Error: 401 Unauthorized at https://api.github.com/repos/yarnpkg/berry/actions/workflows/integration-workflow.yml/runs?per_page=10&page=0
```

I think this means that [the GitHub tokens](https://github.com/sysgears/pinyarn/blob/aff985a7483ad4ba75df9236039f755b435a893b/.pinyarn.js#L10-L23) are expired.

**Comment by larixer** [comment]
Sorry for late reply, this should be fixed in the latest release.
